# Generated by Django 4.0.4 on 2022-05-23 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres_1', models.CharField(blank=True, max_length=96)),
                ('addres_2', models.CharField(blank=True, max_length=96)),
                ('city', models.TextField(blank=True, max_length=30)),
                ('state', models.TextField(blank=True, max_length=30)),
                ('country', models.TextField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
