# Generated by Django 4.0.3 on 2022-03-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_options_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='varation_value',
            new_name='variation_value',
        ),
    ]
