# Generated by Django 4.0.3 on 2022-03-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_descripiton2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='descripiton2',
        ),
    ]
