# Generated by Django 4.0.3 on 2022-03-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_category_descripiton2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
